// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DateCalendar: typeof import('./../components/DateCalendar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Graph: typeof import('./../components/Graph.vue')['default']
    Icon: typeof import('./../components/Icon.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    Radio: typeof import('./../components/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Selector: typeof import('./../components/Selector.vue')['default']
    SelectSingle: typeof import('./../components/SelectSingle.vue')['default']
    Tags: typeof import('./../components/Tags.vue')['default']
    TimePicker: typeof import('./../components/TimePicker.vue')['default']
  }
}

export {}
